name: lab1_19_viharev_shebeta
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: ^0.11.3
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/ 
    - assets/images/
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900